from airbyte_cdk.sources.streams.core import package_name_from_class

from source_kyve.util import CustomResourceSchemaLoader

def test_custom_loader():

    custom_loader = CustomResourceSchemaLoader("source_kyve")
    schema = custom_loader.get_schema("evm/block")
    assert schema == {'$schema': 'http://json-schema.org/draft-04/schema#', 'type': 'object', 'properties': {'key': {'type': 'integer'}, 'value': {'type': 'object', 'properties': {'hash': {'type': 'string'}, 'miner': {'type': 'string'}, 'number': {'type': 'integer'}, 'gasUsed': {'type': 'object', 'properties': {'hex': {'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['hex', 'type']}, 'gasLimit': {'type': 'object', 'properties': {'hex': {'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['hex', 'type']}, 'extraData': {'type': 'string'}, 'timestamp': {'type': 'integer'}, 'difficulty': {'type': 'integer'}, 'parentHash': {'type': 'string'}, '_difficulty': {'type': 'object', 'properties': {'hex': {'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['hex', 'type']}, 'transactions': {'type': 'array', 'items': {'$schema': 'http://json-schema.org/draft-04/schema#', 'type': 'object', 'properties': {'r': {'type': 'string'}, 's': {'type': 'string'}, 'v': {'type': 'integer'}, 'to': {'type': 'string'}, 'raw': {'type': 'string'}, 'data': {'type': 'string'}, 'from': {'type': 'string'}, 'hash': {'type': 'string'}, 'type': {'type': 'integer'}, 'nonce': {'type': 'integer'}, 'value': {'type': 'object', 'properties': {'hex': {'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['hex', 'type']}, 'chainId': {'type': 'integer'}, 'creates': {'type': 'null'}, 'gasLimit': {'type': 'object', 'properties': {'hex': {'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['hex', 'type']}, 'gasPrice': {'type': 'object', 'properties': {'hex': {'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['hex', 'type']}, 'blockHash': {'type': 'string'}, 'accessList': {'type': 'null'}, 'blockNumber': {'type': 'integer'}, 'transactionIndex': {'type': 'integer'}}, 'required': ['r', 's', 'v', 'to', 'raw', 'data', 'from', 'hash', 'type', 'nonce', 'value', 'chainId', 'creates', 'gasLimit', 'gasPrice', 'blockHash', 'accessList', 'blockNumber', 'transactionIndex']}}}, 'required': ['hash', 'miner', 'number', 'gasUsed', 'gasLimit', 'extraData', 'timestamp', 'difficulty', 'parentHash', '_difficulty', 'transactions']}}, 'required': ['key', 'value']}

